name: Main
run-name: ${{ github.actor }} building code and running tests
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: |
          ls ${{ github.workspace }}
      - name: Setup verilator
        run: sudo ./scripts/setup.sh
      - name: Build and run tasks
        run: base_path=$(pwd) for path in $(echo sem*); cd $base_path/$path; cmake -B build -S .; cmake --build build; ./build/exe; done
